## 스프링부트 애플리케이션 개발 환경 설정 - H2 인 메모리 DB

spring:
  # 데이터베이스 연결 정보 설정 
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    # SQL 초기화 설정
    init:
      encoding: UTF-8
      # 초기화 모드 - 내장 데이터베이스 사용시 SQL 스크립트 실행
      mode: EMBEDDED
      # SQL 스크립트 경로 지정
      schema-locations:
        - classpath:sql/schema.sql
      data-locations:
        - classpath:sql/data.sql
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  # 내장 톰캣 서버 포트 번호 변경
  port: 80






